name: GitHub Action - S3, CloudFront, and ECR

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials using OIDC
        uses:  aws-actions/configure-aws-credentials@v1
        with:
            role-to-assume: arn:aws:iam::253490770873:role/Nc-github-action
            aws-region: us-east-2


      - name: Sync index.html to S3
        run: |
          aws s3 sync . s3://nc-s3-deploy --delete

      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation --distribution-id E339T0S8OTBXSJ --paths "/*"

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker image including index.html
        run: |
          docker build -t 253490770873.dkr.ecr.us-east-2.amazonaws.com/nr-registry-test:latest .

      - name: Push Docker image to ECR
        run: |
          docker push 253490770873.dkr.ecr.us-east-2.amazonaws.com/nr-registry-test:latest
