name: Deploy to S3 and Invalidate CloudFront CICD Week

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::253490770873:role/nc-git-2  # Tu rol actualizado
          aws-region: us-east-2  # La región donde estás trabajando

      - name: Deploy to S3
        run: |
          aws s3 sync . s3://nc-s3-deploy --delete  # Tu bucket de S3 actualizado

      - name: Create CloudFront Invalidation
        run: |
          aws cloudfront create-invalidation --distribution-id E339T0S8OTBXSJ --paths "/*"  # Tu distribución de CloudFront actualizada

